# .github/workflows/ci.yaml
name: CI Pipeline

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', 'docs/**']
  pull_request:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  # ⚠️ terraform output으로 확인한 실제 값으로 변경!
  ECR_REGISTRY: 904053119728.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: gitops-app

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # ⚠️ terraform output으로 확인한 실제 값!
          role-to-assume: arn:aws:iam::904053119728:role/gitops-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        id: build
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          DATE=$(date +%y%m%d)
          IMAGE_TAG="v1.0.0-${DATE}-${SHORT_SHA}"

          FULL_IMAGE="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${IMAGE_TAG}"

          docker build -t ${FULL_IMAGE} .
          docker push ${FULL_IMAGE}

          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT